
language: python
python:
  - "3.7"
  - "nightly"
install:
  - "pip install -r requirements.txt"
script:
  - cd med_files_api && flake8 cmdbox
  - coverage run manage.py test
after_success:
  - codecov