version: '3'

services:
    api:
        build: .
        command: python med_files_api/manage.py runserver 0.0.0.0:8001
        ports:
            - "8001:8001"
        volumes:
            - .:/code
        depends_on:
            - db
        networks:
            - backend
        environment:
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}

    db:
        image: postgres
        hostname: db
        ports:
            - "5432:5432"
        expose:
            - "5432"
        volumes:
            - ./postgresql_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        networks:
            - backend

networks:
    backend:
        driver: bridge