version: '3'

services:
    api:
        build: .
        command: >
            sh -c "cd med_files_api &&
            python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8001"
        ports:
            - "8001:8001"
        volumes:
            - .:/code
        depends_on:
            - db
        networks:
            - backend
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}

    db:
        image: postgres
        hostname: db
        ports:
            - "5432:5432"
        expose:
            - "5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        networks:
            - backend
    db-admin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        depends_on:
            - db
        ports:
            - "8080:80"
        networks:
            - backend


networks:
    backend:
        driver: bridge