# Generated by Django 3.0.5 on 2020-05-09 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('med_result', '0005_auto_20200509_1038'),
        ('doctor', '0011_auto_20200504_1401'),
        ('core', '0003_tag'),
        ('medicine', '0006_auto_20200503_1511'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('adres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Doctor')),
                ('med_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='med_result.MedResult')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.Medicine')),
                ('tag', models.ManyToManyField(blank=True, to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
