# Generated by Django 3.0.5 on 2020-05-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20200509_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_time',
        ),
    ]
