# Generated by Django 3.0.5 on 2020-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_remove_visit_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(blank=True),
        ),
    ]
