# Generated by Django 3.0.5 on 2020-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20200509_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
