# Generated by Django 3.0.5 on 2020-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20200503_1511'),
        ('visit', '0008_auto_20200509_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='medicine',
        ),
        migrations.AddField(
            model_name='visit',
            name='medicine',
            field=models.ManyToManyField(blank=True, to='medicine.Medicine'),
        ),
    ]
