# Generated by Django 3.0.5 on 2020-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_result', '0005_auto_20200509_1038'),
        ('visit', '0009_auto_20200509_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='med_result',
        ),
        migrations.AddField(
            model_name='visit',
            name='med_result',
            field=models.ManyToManyField(blank=True, to='med_result.MedResult'),
        ),
    ]
