# Generated by Django 3.0.5 on 2020-05-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0010_auto_20200509_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='adres',
            new_name='address',
        ),
    ]
