# Generated by Django 3.0.5 on 2020-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('med_form', models.CharField(choices=[('TAB', 'Tablets'), ('SYR', 'Surup'), ('DRO', 'Drops'), ('OIN', 'Ointment'), ('GLO', 'Globules')], default='TAB', max_length=3, verbose_name='Form')),
                ('med_type', models.CharField(choices=[('ANT', 'Antybiotic'), ('PRO', 'Probiotic'), ('VIT', 'Vitamin'), ('SUP', 'Suplement')], default='VIT', max_length=3, verbose_name='Type')),
            ],
        ),
    ]
