# Generated by Django 3.0.5 on 2020-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='medicine per user'),
        ),
    ]
