# Generated by Django 3.0.5 on 2020-05-03 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0002_auto_20200503_1431'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicine',
            name='medicine per user',
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('user', 'name')},
        ),
    ]
