# Generated by Django 3.0.5 on 2020-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20200503_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='medicine per user'),
        ),
    ]
