# Generated by Django 3.0.5 on 2020-05-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20200503_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='form',
            new_name='med_form',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='_type',
            new_name='med_type',
        ),
    ]
