# Generated by Django 3.0.5 on 2020-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='born_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
