# Generated by Django 3.0.5 on 2020-04-26 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('adres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Phone Number')),
                ('doc_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorSpecialization', verbose_name='Specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
