# Generated by Django 3.0.5 on 2020-04-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialization',
            name='specialization',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
