# Generated by Django 3.0.5 on 2020-04-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20200427_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doc_spec',
            new_name='doc_specialization',
        ),
        migrations.RenameField(
            model_name='doctorspecialization',
            old_name='specialization',
            new_name='name',
        ),
    ]
