# Generated by Django 3.0.5 on 2020-04-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200428_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='doctor.DoctorSpecialization', verbose_name='Specialization'),
        ),
    ]
