# Generated by Django 3.0.5 on 2020-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20200428_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number'),
        ),
    ]
