# Generated by Django 3.0.5 on 2020-04-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20200428_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doc_specialization',
            new_name='specialization',
        ),
    ]
