# Generated by Django 3.0.5 on 2020-05-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20200502_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('URO', 'Urologis'), ('ORT', 'Orthopedist'), ('OPH', 'Ophthalmologist'), ('NEU', 'Neurologist'), ('SUR', 'Surgeon'), ('LAR', 'Laryngologist'), ('GYN', 'Gynecologist'), ('FDO', 'Family doctor'), ('CAR', 'Cardiologist'), ('ONC', 'Oncologist'), ('GAS', 'Gastroenterologist'), ('END', 'Endocrinologist'), ('DER', 'Dermatologist'), ('ALL', 'Allergist')], default='FDO', max_length=3, verbose_name='Specialization'),
        ),
    ]
