# Generated by Django 3.0.5 on 2020-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20200502_1745'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='doctor per user'),
        ),
    ]
