# Generated by Django 3.0.5 on 2020-04-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('medicine_form', models.CharField(choices=[('TAB', 'Tablets'), ('SYR', 'Surup'), ('DRO', 'Drops'), ('OIN', 'Oinment')], default='TAB', max_length=3, verbose_name='Form')),
                ('medicine_type', models.CharField(choices=[('ANT', 'Antybiotic'), ('PRO', 'Probiotic'), ('VIT', 'Vitamin')], default='VIT', max_length=3, verbose_name='Type')),
                ('when_added', models.DateTimeField(auto_now_add=True, verbose_name='When added')),
            ],
        ),
    ]
