# Generated by Django 3.0.5 on 2020-04-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='medicine_form',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='medicine_type',
        ),
        migrations.AddField(
            model_name='medicines',
            name='med_form',
            field=models.CharField(choices=[('TAB', 'Tablets'), ('SYR', 'Surup'), ('DRO', 'Drops'), ('OIN', 'Ointment'), ('GLO', 'Globules')], default='TAB', max_length=3, verbose_name='Form'),
        ),
        migrations.AddField(
            model_name='medicines',
            name='med_type',
            field=models.CharField(choices=[('ANT', 'Antybiotic'), ('PRO', 'Probiotic'), ('VIT', 'Vitamin'), ('SUP', 'Suplement')], default='VIT', max_length=3, verbose_name='Type'),
        ),
    ]
