# Generated by Django 3.0.5 on 2020-04-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_auto_20200406_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='when_added',
        ),
        migrations.AlterField(
            model_name='medicines',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Name'),
        ),
    ]
