# Generated by Django 3.0.5 on 2020-04-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20200407_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicines',
            new_name='Medicine',
        ),
    ]
